version: '3.4'

services:
  pifancontrol:
    image: sbv1307/pi-fan-control:latest
    restart: always
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
    volumes:
      - /opt/vc:/opt/vc:ro
    devices:
      - /dev/vchiq
    privileged: true
    stdin_open: true
    tty: true
